/**
 * Thin abstraction over QuickBEAM's global `Beam` API.
 *
 * In a live QuickBEAM runtime, `Beam` is a global object exposing
 * process primitives. This module re-exports those primitives and
 * allows them to be overridden for testing via `setMockBeam()`.
 *
 * @module beam-shim
 */

/**
 * Opaque process identifier assigned by the BEAM.
 * In QuickBEAM this is a string-encoded pid like `"<0.123.0>"`.
 */
export type BeamPid = string;

/**
 * Opaque reference for matching call/reply pairs.
 * Generated by `Beam.makeRef()`.
 */
export type BeamRef = string;

/**
 * Monitor reference returned by `Beam.monitor()`.
 */
export type BeamMonitorRef = string;

/**
 * A message handler callback registered via `Beam.onMessage()`.
 * Returns `void` if the process should continue, or a value if it should exit.
 */
export type BeamMessageHandler = (message: any) => void | Promise<void>;

/**
 * Callback invoked when a monitored process exits.
 */
export type BeamMonitorCallback = (pid: BeamPid, reason: any) => void;

// ── Interface ──────────────────────────────────────────────────────

export interface BeamAPI {
  /** Spawn a new JS runtime process. Returns the new PID. */
  spawn(fn: () => Promise<void> | void, args?: any): Promise<BeamPid>;

  /** Get the PID of the current process. */
  self(): BeamPid;

  /** Send a message to a process. */
  send(pid: BeamPid, message: any): void;

  /** Register a message handler for the current process. */
  onMessage(handler: BeamMessageHandler): void;

  /** Register the current process under a name. */
  register(name: string, pid: BeamPid): void;

  /** Look up a PID by registered name. Returns undefined if not found. */
  whereis(name: string): BeamPid | undefined;

  /** Unregister a name. */
  unregister(name: string): void;

  /** Monitor a process. Calls `cb` when `pid` exits. */
  monitor(pid: BeamPid, cb: BeamMonitorCallback): BeamMonitorRef;

  /** Stop monitoring a process. */
  demonitor(ref: BeamMonitorRef): void;

  /** Link the current process to another. Crash propagation. */
  link(pid: BeamPid): void;

  /** Unlink from a process. */
  unlink(pid: BeamPid): void;

  /** Generate a unique reference for call/reply matching. */
  makeRef(): BeamRef;

  /** Exit the current process with a reason. */
  exit(reason: any): void;

  /** Send an exit signal to another process. */
  exitProcess(pid: BeamPid, reason: any): void;

  /** List connected BEAM nodes. */
  nodes(): string[];

  /** Synchronous RPC to a named process (blocks the caller). */
  callSync(target: string | BeamPid, message: any, timeout?: number): any;

  /** Asynchronous RPC to a named process. */
  call(target: string | BeamPid, message: any, timeout?: number): Promise<any>;

  /** Evaluate JavaScript code (or a closure) in the context of a target process.
   *  Allows transporting closures and scope across processes. */
  eval(target: BeamPid, code: string | ((scope: any) => void | Promise<void>), scope?: any): Promise<void>;

  /** Sleep for `ms` milliseconds (non-blocking in BEAM terms). */
  sleep(ms: number): Promise<void>;
}

// ── Implementation ─────────────────────────────────────────────────

let _beam: BeamAPI | null = null;

/**
 * Get the current Beam API — either a mock (set via setMockBeam) or
 * the global `Beam` object provided by QuickBEAM.
 */
export function getBeam(): BeamAPI {
  if (_beam) return _beam;
  if (typeof globalThis !== "undefined" && (globalThis as any).Beam) {
    return (globalThis as any).Beam as BeamAPI;
  }
  throw new Error(
    "Beam API not available. Are you running inside a QuickBEAM runtime? " +
    "For testing, call setMockBeam() first."
  );
}

/**
 * Override the Beam API (for testing). Pass `null` to restore
 * the default (global Beam) behavior.
 */
export function setMockBeam(mock: BeamAPI | null): void {
  _beam = mock;
}

// ── Convenience re-exports ─────────────────────────────────────────

export const Beam = {
  get spawn() { return getBeam().spawn.bind(getBeam()); },
  get self() { return getBeam().self.bind(getBeam()); },
  get send() { return getBeam().send.bind(getBeam()); },
  get onMessage() { return getBeam().onMessage.bind(getBeam()); },
  get register() { return getBeam().register.bind(getBeam()); },
  get whereis() { return getBeam().whereis.bind(getBeam()); },
  get unregister() { return getBeam().unregister.bind(getBeam()); },
  get monitor() { return getBeam().monitor.bind(getBeam()); },
  get demonitor() { return getBeam().demonitor.bind(getBeam()); },
  get link() { return getBeam().link.bind(getBeam()); },
  get unlink() { return getBeam().unlink.bind(getBeam()); },
  get makeRef() { return getBeam().makeRef.bind(getBeam()); },
  get exit() { return getBeam().exit.bind(getBeam()); },
  get exitProcess() { return getBeam().exitProcess.bind(getBeam()); },
  get nodes() { return getBeam().nodes.bind(getBeam()); },
  get callSync() { return getBeam().callSync.bind(getBeam()); },
  get call() { return getBeam().call.bind(getBeam()); },
  get eval() { return getBeam().eval.bind(getBeam()); },
  get sleep() { return getBeam().sleep.bind(getBeam()); },
};
